<?xml version="1.0" encoding="utf-8"?><Database Name="proyectonet" Class="Db_persona_entDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=proyectonet;Persist Security Info=True;User ID=mchoc" SettingsObjectName="NegocioCls.Properties.Settings" SettingsPropertyName="proyectonetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="persona.persona" Member="personas">
    <Type Name="persona">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>